# Generated by Django 2.0.1 on 2018-01-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberId', models.AutoField(primary_key=True, serialize=False)),
                ('memberCode', models.CharField(max_length=20)),
                ('memberFullName', models.CharField(max_length=100)),
                ('memberAddress', models.CharField(max_length=100)),
                ('memberPhoneNum', models.IntegerField()),
            ],
            options={
                'db_table': 'member',
                'ordering': ['memberCode'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('memberId', 'memberCode')},
        ),
    ]
